repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        -   id: mixed-line-ending
            args: ["-f", "lf"]
        -   id: check-yaml
        -   id: check-toml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: double-quote-string-fixer
  -   repo: https://github.com/psf/black
      rev: '24.4.0'
      hooks:
        -   id: black
            args:
              - "-S"
              - "-l"
              - "120"
  -   repo: https://github.com/asottile/reorder-python-imports
      rev: v3.12.0
      hooks:
        -   id: reorder-python-imports
